### ISSUE TITLE
Front running question

### ISSUE THREAD

**Issue by mingrui** [HydroProtocol/protocol#5]
Hi,

Is there a documentation that explains how hydro protocol prevents front running?

Thank you!

**Comment by swinges** [comment]
Thanks for reaching out! We will throw up some more official writing on this in our developer documentation in the future.

As for now, we have discussed this a bit in a few articles and blog posts: https://medium.com/hydro-protocol/breaking-down-the-flash-boys-dex-trading-bots-bloomberg-article-49c18eb649ac is probably the most significant for discussing front running specifically.

At a high level, trader vs trader front running is an artifact of a system with **on-chain matching**. Hydro Protocol DEX's use the Hybrid approach, where matching is done off-chain. Because the orders can only be matched by the relayer in a Hydro system, the relayer takes an order off the books instantly when they match an order. There is no waiting on a blockchain confirmation for the matching process: there's no window for someone else to come in and snipe the order out from under the initial order filler.

This prevents a wide variety of problems associated with trader vs trader front running: gas-price auctions, failed orders, market order slippage, etc.

Let me know if I can help clarify any of this :)

**Comment by mingrui** [comment]
thx!
